import os


MAPBOX_API_KEY = os.environ['MAPBOX_API_KEY']
TWILIO_ACCOUNT_SID = os.environ['TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = os.environ['TWILIO_AUTH_TOKEN']
TWILIO_MAIN_PHONE_NUMBER = os.environ['TWILIO_MAIN_PHONE_NUMBER']
